// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6iia2353HlEK8Xzp8u0xPAg_pjlTHqFM',
    appId: '1:257318589642:web:8f453933ac8c3a22235033',
    messagingSenderId: '257318589642',
    projectId: 'ride-move',
    authDomain: 'ride-move.firebaseapp.com',
    databaseURL: 'https://ride-move-default-rtdb.firebaseio.com',
    storageBucket: 'ride-move.appspot.com',
    measurementId: 'G-FXK8V2Y03F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBenZZ4X5Owq9kA9MM2zrJq9RUvwidPd-o',
    appId: '1:257318589642:android:3cfcdae9c41e5831235033',
    messagingSenderId: '257318589642',
    projectId: 'ride-move',
    databaseURL: 'https://ride-move-default-rtdb.firebaseio.com',
    storageBucket: 'ride-move.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZJQYQbQzdZ95_jN8bE41GZq9I_9jNU7w',
    appId: '1:257318589642:ios:23c80c2bc232d6f3235033',
    messagingSenderId: '257318589642',
    projectId: 'ride-move',
    databaseURL: 'https://ride-move-default-rtdb.firebaseio.com',
    storageBucket: 'ride-move.appspot.com',
    iosClientId: '257318589642-eq4mkf5e8hbcvatmdieo45fdk65ugbtf.apps.googleusercontent.com',
    iosBundleId: 'com.example.openstreetmap',
  );
}
