// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyC38dUucuCo7XKjJJZuC-Ssv7xzEI5P7G4",
    authDomain: "kiwi-city.firebaseapp.com",
    databaseURL: "https://kiwi-city-default-rtdb.firebaseio.com",
    projectId: "kiwi-city",
    storageBucket: "kiwi-city.appspot.com",
    messagingSenderId: "71253473213",
    appId: "1:71253473213:web:ef6b8bdb0081604a7204d4",
    measurementId: "G-VQ5EZWNQHQ",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1fxtUagoG5mInMobTBwPegUyZ84Y0rsA',
    appId: '1:71253473213:android:c19bb5330fbe85127204d4',
    messagingSenderId: '71253473213',
    projectId: 'kiwi-city',
    databaseURL: 'https://kiwi-city-default-rtdb.firebaseio.com',
    storageBucket: 'kiwi-city.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW21HIZqugLnr1OAuWNaqyCaZGCBi0BB8',
    appId: '1:71253473213:ios:c2f086aee2aba3ef7204d4',
    messagingSenderId: '71253473213',
    projectId: 'kiwi-city',
    databaseURL: 'https://kiwi-city-default-rtdb.firebaseio.com',
    storageBucket: 'kiwi-city.appspot.com',
    iosClientId:
        '71253473213-mnjcumqv2ac09ttpbj79tn2q7e4kk8hd.apps.googleusercontent.com',
    iosBundleId: 'com.kiwicity.co',
  );
}
